package org.strykeforce.thirdcoast.talon.phoenix6

import com.ctre.phoenix6.controls.CoastOut
import com.ctre.phoenix6.controls.ControlRequest
import com.ctre.phoenix6.controls.DifferentialDutyCycle
import com.ctre.phoenix6.controls.DifferentialFollower
import com.ctre.phoenix6.controls.DifferentialMotionMagicDutyCycle
import com.ctre.phoenix6.controls.DifferentialMotionMagicVoltage
import com.ctre.phoenix6.controls.DifferentialPositionDutyCycle
import com.ctre.phoenix6.controls.DifferentialPositionVoltage
import com.ctre.phoenix6.controls.DifferentialStrictFollower
import com.ctre.phoenix6.controls.DifferentialVelocityDutyCycle
import com.ctre.phoenix6.controls.DifferentialVelocityVoltage
import com.ctre.phoenix6.controls.DifferentialVoltage
import com.ctre.phoenix6.controls.DutyCycleOut
import com.ctre.phoenix6.controls.DynamicMotionMagicDutyCycle
import com.ctre.phoenix6.controls.DynamicMotionMagicTorqueCurrentFOC
import com.ctre.phoenix6.controls.DynamicMotionMagicVoltage
import com.ctre.phoenix6.controls.Follower
import com.ctre.phoenix6.controls.MotionMagicDutyCycle
import com.ctre.phoenix6.controls.MotionMagicExpoDutyCycle
import com.ctre.phoenix6.controls.MotionMagicExpoTorqueCurrentFOC
import com.ctre.phoenix6.controls.MotionMagicExpoVoltage
import com.ctre.phoenix6.controls.MotionMagicTorqueCurrentFOC
import com.ctre.phoenix6.controls.MotionMagicVelocityDutyCycle
import com.ctre.phoenix6.controls.MotionMagicVelocityTorqueCurrentFOC
import com.ctre.phoenix6.controls.MotionMagicVelocityVoltage
import com.ctre.phoenix6.controls.MotionMagicVoltage
import com.ctre.phoenix6.controls.MusicTone
import com.ctre.phoenix6.controls.PositionDutyCycle
import com.ctre.phoenix6.controls.PositionTorqueCurrentFOC
import com.ctre.phoenix6.controls.PositionVoltage
import com.ctre.phoenix6.controls.StaticBrake
import com.ctre.phoenix6.controls.StrictFollower
import com.ctre.phoenix6.controls.TorqueCurrentFOC
import com.ctre.phoenix6.controls.VelocityDutyCycle
import com.ctre.phoenix6.controls.VelocityTorqueCurrentFOC
import com.ctre.phoenix6.controls.VelocityVoltage
import com.ctre.phoenix6.controls.VoltageOut
import com.ctre.phoenix6.signals.MotorAlignmentValue
import com.ctre.phoenix6.signals.NeutralModeValue
import edu.wpi.first.wpilibj.Timer
import mu.KotlinLogging
import net.consensys.cava.toml.TomlTable
import org.jline.reader.EndOfFileException
import org.koin.core.component.inject
import org.strykeforce.thirdcoast.command.AbstractCommand
import org.strykeforce.thirdcoast.command.Command
import org.strykeforce.thirdcoast.command.prompt
import org.strykeforce.thirdcoast.device.*
import org.strykeforce.thirdcoast.warn

private val logger = KotlinLogging.logger{}

