type = "menu"
[talon]
  type = "menu"
  order = 10
  menu = "work with talons"
  [talon.select]
    type = "talon.select"
    order = 10
    menu = "select active talons"
  [talon.mode]
    type = "talon.mode.select"
    order = 15
    menu = "control mode"
  [talon.slot]
    type = "menu"
    order = 20
    menu = "configure PID slots"
    [talon.slot.select]
      type = "talon.slot.select"
      order = 10
      menu = "active slot"
    [talon.slot.P]
      type ="talon.slot.param"
      order = 20
      param = "eProfileParamSlot_P"
    [talon.slot.I]
      type ="talon.slot.param"
      order = 30
      param = "eProfileParamSlot_I"
    [talon.slot.D]
      type ="talon.slot.param"
      order = 40
      param = "eProfileParamSlot_D"
    [talon.slot.F]
      type ="talon.slot.param"
      order = 50
      param = "eProfileParamSlot_F"
    [talon.slot.IZone]
      type ="talon.slot.param"
      order = 60
      param = "eProfileParamSlot_IZone"
    [talon.slot.AllowableErr]
      type ="talon.slot.param"
      order = 70
      param = "eProfileParamSlot_AllowableErr"
    [talon.slot.MaxIAccum]
      type ="talon.slot.param"
      order = 80
      param = "eProfileParamSlot_MaxIAccum"
    [talon.slot.PeakOutput]
      type ="talon.slot.param"
      order = 90
      param = "eProfileParamSlot_PeakOutput"
  [talon.run]
    type = "talon.run"
    order = 30
    menu = "run active talons"
  [talon.config]
    type = "menu"
    order = 40
    menu = "configure active talons"
    [talon.config.output]
      type = "config"
      order = 100
      menu = "configure selected Talons output parameters"
    [talon.config.sensor]
      type = "config"
      order = 200
      menu = "configure selected Talons sensors"
  [talon.status]
    type = "talon.status"
    order = 50
    menu = "status of active talons"

[dio]
  type = "menu"
  order = 20
  menu = "work with digital I/O"
  [dio.status]
    type = "status"
    order = 10
    menu = "status of selected digital inputs"
  [dio.set]
    type = "command"
    order = 20
    menu = "set selected digital output"

[servo]
  type = "menu"
  order = 30
  menu = "work with servos"
  [servo.set]
    type = "command"
    order = 10
    menu = "run selected servos"

[test]
  type = "test"
  order = 99
