type = "menu"
[talon]
  type = "menu"
  order = 1
  menu = "work with Talons"
  [talon.select]
    type = "talon.select"
    order = 1
    menu = "select Talons"
  [talon.slot]
    type = "menu"
    order = 5
    menu = "PID slot parameters"
    [talon.slot.k_P]
      type ="talon.slot.param"
      menu = "P"
      [talon.slot.k_P.param]
        name = "P"
        type = "DOUBLE"
        desc = "Sets the 'P' constant in the given parameter slot."
    [talon.slot.k_I]
      type ="talon.slot.param"
      menu = "I"
      [talon.slot.k_I.param]
        name = "I"
        type = "DOUBLE"
        desc = "Sets the 'I' constant in the given parameter slot."
    [talon.slot.k_D]
      type ="talon.slot.param"
      menu = "D"
      [talon.slot.k_D.param]
        name = "D"
        type = "DOUBLE"
        range = [-12.0, 12.0]
        desc = "Sets the 'D' constant in the given parameter slot."
    [talon.slot.k_F]
      type ="talon.slot.param"
      menu = "F"
      [talon.slot.k_F.param]
        name = "F"
        type = "DOUBLE"
        desc = "Sets the 'F' constant in the given parameter slot."
  [talon.status]
    type = "talon.status"
    order = 10
    menu = "status of selected Talons"
  [talon.config]
    type = "menu"
    order = 20
    menu = "configure selected Talons"
    [talon.config.output]
      type = "config"
      order = 100
      menu = "configure selected Talons output parameters"
    [talon.config.sensor]
      type = "config"
      order = 200
      menu = "configure selected Talons sensors"
  [talon.set]
    type = "command"
    order = 30
    menu = "run selected Talons"

[dio]
  type = "menu"
  order = 2
  menu = "work with digital I/O"
  [dio.status]
    type = "status"
    order = 10
    menu = "status of selected digital inputs"
  [dio.set]
    type = "command"
    order = 20
    menu = "set selected digital output"

[servo]
  type = "menu"
  order = 3
  menu = "work with servos"
  [servo.set]
    type = "command"
    order = 10
    menu = "run selected servos"

[test]
  type = "test"
  order = 99
