type = "menu"
[talon]
  type = "menu"
  order = 1
  menu = "work with Talons"
  [talon.select]
    type = "talon.select"
    order = 1
    menu = "select Talons"
  [talon.slot]
    type = "menu"
    order = 5
    menu = "PID slot parameters"
    [talon.slot.P]
      type ="talon.slot.param"
      order = 0
      param = "eProfileParamSlot_P"
    [talon.slot.I]
      type ="talon.slot.param"
      order = 1
      param = "eProfileParamSlot_I"
    [talon.slot.D]
      type ="talon.slot.param"
      order = 2
      param = "eProfileParamSlot_D"
    [talon.slot.F]
      type ="talon.slot.param"
      order = 3
      param = "eProfileParamSlot_F"
    [talon.slot.IZone]
      type ="talon.slot.param"
      order = 4
      param = "eProfileParamSlot_IZone"
    [talon.slot.AllowableErr]
      type ="talon.slot.param"
      order = 5
      param = "eProfileParamSlot_AllowableErr"
    [talon.slot.MaxIAccum]
      type ="talon.slot.param"
      order = 6
      param = "eProfileParamSlot_MaxIAccum"
    [talon.slot.PeakOutput]
      type ="talon.slot.param"
      order = 7
      param = "eProfileParamSlot_PeakOutput"
  [talon.status]
    type = "talon.status"
    order = 10
    menu = "status of selected Talons"
  [talon.config]
    type = "menu"
    order = 20
    menu = "configure selected Talons"
    [talon.config.output]
      type = "config"
      order = 100
      menu = "configure selected Talons output parameters"
    [talon.config.sensor]
      type = "config"
      order = 200
      menu = "configure selected Talons sensors"
  [talon.set]
    type = "command"
    order = 30
    menu = "run selected Talons"

[dio]
  type = "menu"
  order = 2
  menu = "work with digital I/O"
  [dio.status]
    type = "status"
    order = 10
    menu = "status of selected digital inputs"
  [dio.set]
    type = "command"
    order = 20
    menu = "set selected digital output"

[servo]
  type = "menu"
  order = 3
  menu = "work with servos"
  [servo.set]
    type = "command"
    order = 10
    menu = "run selected servos"

[test]
  type = "test"
  order = 99
