type = "menu"
[talon]
  type = "menu"
  order = 10
  menu = "work with talons"
  [talon.select]
    type = "talon.select"
    order = 10
    menu = "select active talons"
  [talon.run]
    type = "talon.run"
    order = 12
    menu = "run active talons"
  [talon.mode]
    type = "talon.mode"
    order = 15
    menu = "control mode"
  [talon.sensor]
    type = "menu"
    order = 17
    menu = "configure feedback sensors"
    [talon.sensor.primary]
      type = "talon.sensor"
      order = 10
      menu = "primary closed-loop sensor"
      pid = 0
    [talon.sensor.auxiliary]
      type = "talon.sensor"
      order = 20
      menu = "auxiliary closed-loop sensor"
      pid = 1
  [talon.slot]
    type = "menu"
    order = 20
    menu = "configure PID slots"
    [talon.slot.select]
      type = "talon.slot.select"
      order = 10
      menu = "active slot"
    [talon.slot.P]
      type ="talon.slot.param"
      order = 20
      param = "SLOT_P"
    [talon.slot.I]
      type ="talon.slot.param"
      order = 30
      param = "SLOT_I"
    [talon.slot.D]
      type ="talon.slot.param"
      order = 40
      param = "SLOT_D"
    [talon.slot.F]
      type ="talon.slot.param"
      order = 50
      param = "SLOT_F"
    [talon.slot.IZone]
      type ="talon.slot.param"
      menu = "I Zone"
      order = 60
      param = "SLOT_I_ZONE"
    [talon.slot.AllowableErr]
      type ="talon.slot.param"
      menu = "Allowable Error"
      order = 70
      param = "SLOT_ALLOWABLE_ERR"
    [talon.slot.MaxIAccum]
      type ="talon.slot.param"
      menu = "Max I Accum"
      order = 80
      param = "SLOT_MAX_I_ACCUM"
    [talon.slot.PeakOutput]
      type ="talon.slot.param"
      menu = "Peak output"
      order = 90
      param = "SLOT_PEAK_OUTPUT"
  [talon.motion_magic]
    type = "menu"
    order = 22
    menu = "configure motion magic"
    [talon.motion_magic.cruise_velocity]
      type = "talon.param"
      order = 10
      menu = "motion magic cruise velocity"
      param = "MOTION_CRUISE_VELOCITY"
    [talon.motion_magic.acceleration]
      type = "talon.param"
      order = 20
      menu = "motion magic acceleration"
      param = "MOTION_ACCELERATION"
  [talon.output]
    type = "menu"
    order = 25
    menu = "configure motor output"
    [talon.output.brake]
      type = "talon.brake"
      order = 10
      menu = "brake mode"
    [talon.output.reversed]
      type = "talon.param"
      order = 20
      menu = "motor output reversed"
      param = "OUTPUT_REVERSED"
    [talon.output.open-loop_ramp]
      type = "talon.param"
      order = 30
      menu = "open-loop ramp rate"
      param = "OPEN_LOOP_RAMP"
    [talon.output.closed-loop_ramp]
      type = "talon.param"
      order = 40
      menu = "closed-loop ramp rate"
      param = "CLOSED_LOOP_RAMP"
    [talon.output.forward_peak_output]
      type = "talon.param"
      order = 50
      menu = "forward peak output"
      param = "PEAK_OUTPUT_FORWARD"
    [talon.output.reverse_peak_output]
      type = "talon.param"
      order = 60
      menu = "reverse peak output"
      param = "PEAK_OUTPUT_REVERSE"
    [talon.output.forward_nominal_output]
      type = "talon.param"
      order = 70
      menu = "forward nominal output"
      param = "NOMINAL_OUTPUT_FORWARD"
    [talon.output.reverse_nominal_output]
      type = "talon.param"
      order = 80
      menu = "reverse nominal output"
      param = "NOMINAL_OUTPUT_REVERSE"
    [talon.output.neutral_deadband]
      type = "talon.param"
      order = 90
      menu = "neutral deadband"
      param = "NEUTRAL_DEADBAND"
  [talon.voltage_compensation]
    type = "menu"
    order = 27
    menu = "configure voltage compensation"
    [talon.voltage_compensation.enabled]
      type = "talon.param"
      order = 10
      menu = "voltage compensation enabled"
      param = "VOLTAGE_COMP_ENABLE"
    [talon.voltage_compensation.saturation_voltage]
      type = "talon.param"
      order = 20
      menu = "voltage compensation saturation voltage"
      param = "VOLTAGE_COMP_SATURATION"
    [talon.voltage_compensation.filter]
      type = "talon.param"
      order = 30
      menu = "voltage compensation measurement filter"
      param = "VOLTAGE_MEASUREMENT_FILTER"
  [talon.status]
    type = "talon.status"
    order = 50
    menu = "status of active talons"

[dio]
  type = "menu"
  order = 20
  menu = "work with digital I/O"
  [dio.status]
    type = "status"
    order = 10
    menu = "status of selected digital inputs"
  [dio.set]
    type = "command"
    order = 20
    menu = "set selected digital output"

[servo]
  type = "menu"
  order = 30
  menu = "work with servos"
  [servo.set]
    type = "command"
    order = 10
    menu = "run selected servos"

[test]
  type = "test"
  order = 99
