#
# motor output
#
[OUTPUT_REVERSED]
  name = "Motor Output Reversed"
  type = "BOOLEAN"
  help = "Inverts the H-bridge output of the motor controller. This does not impact sensor phase and should not be used to correct sensor polarity. This will invert the hbridge output but NOT the LEDs. This ensures.... Green LEDs always represents positive request from robot-controller/closed-looping mode. Green LEDs correlates to forward limit switch. Green LEDs correlates to forward soft limit."
[OPEN_LOOP_RAMP]
  name = "Open-Loop Ramp Rate"
  type = "DOUBLE"
  range = [0.0, 1000.0]
  help = "Sets the minimum desired time in seconds to go from neutral to full throttle. A value of '0' will disable the ramp."
[CLOSED_LOOP_RAMP]
  name = "Closed-Loop Ramp Rate"
  type = "DOUBLE"
  range = [0.0, 1000.0]
  help = "Sets the minimum desired time in seconds to go from neutral to full throttle. A value of '0' will disable the ramp."
[PEAK_OUTPUT_FORWARD]
  name = "Foward Peak Output"
  type = "DOUBLE"
  range = [0.0, 1.0]
  help = "Sets the forward peak output percentage from 0 to 1."
[PEAK_OUTPUT_REVERSE]
  name = "Reverse Peak Output"
  type = "DOUBLE"
  range = [-1.0, 0.0]
  help = "Sets the reverse peak output percentage from 0 to 1."
[NOMINAL_OUTPUT_FORWARD]
  name = "Foward Nominal Output"
  type = "DOUBLE"
  range = [0.0, 1.0]
  help = "Sets the forward nominal output percentage from 0 to 1."
[NOMINAL_OUTPUT_REVERSE]
  name = "Reverse Nominal Output"
  type = "DOUBLE"
  range = [-1.0, 0.0]
  help = "Sets the reverse nominal output percentage from 0 to 1."
[NEUTRAL_DEADBAND]
  name = "Neutral Deadband"
  type = "DOUBLE"
  range = [0.001, 0.25]
  help = "Desired deadband percentage. Minimum is 0.1%, Maximum is 25%.  Enter 0.04 for 4% (factory default)."

#
# PID slots
#
[SLOT_P]
  name = "P"
  type = "DOUBLE"
  help = "Sets the P constant in the selected parameter slot."
[SLOT_I]
  name = "I"
  type = "DOUBLE"
  help = "Sets the I constant in the selected parameter slot."
[SLOT_D]
  name = "D"
  type = "DOUBLE"
  help = "Sets the D constant in the selected parameter slot."
[SLOT_F]
  name = "F"
  type = "DOUBLE"
  help = "Sets the F constant in the selected parameter slot."
[SLOT_I_ZONE]
  name = "Integral Zone"
  type = "INTEGER"
  help = "Sets the Integral Zone (closed-loop error units * 1ms) constant in the selected parameter slot. If the (absolute) closed-loop error is outside of this zone, integral accumulator is automatically cleared."
[SLOT_ALLOWABLE_ERR]
  name = "Allowable Closed-Loop Error"
  type = "INTEGER"
  help = "Sets the allowable closed-loop error in the selected parameter slot."
[SLOT_MAX_I_ACCUM]
  name = "Maximum Integral Accumulator"
  type = "DOUBLE"
  help = "Sets the maximum integral accumulator (closed-loop error units * 1ms) in the selected parameter slot."
[SLOT_PEAK_OUTPUT]
  name = "Peak Closed-Loop Output"
  type = "DOUBLE"
  range = [0.0, 1.0]
  help = "Sets the absolute value of peak closed-loop output from 0 to 1 in the selected parameter slot. This setting is applied to the output of the associated PID loop and is seperate from the generic peak output setting."
