type = "menu"
[entry_1]
  type = "default"
  order = 1
  menu = "entry 1"
[entry_2]
  type = "default"
  order = 2
  menu = "entry 2"
[entry_3]
  type = "default"
  order = 3
  menu = "entry 3"
[entry_4]
  type = "default"
  order = 4
[entry_5]
  type = "default"
  order = 5
[entry_6]
  type = "default"
  order = 6
[entry_7]
  type = "default"
  order = 7
[entry_8]
  type = "default"
  order = 8
[entry_9]
  type = "default"
  order = 9
[entry_a]
  type = "default"
  order = 10
[entry_c]
  type = "default"
  order = 11
[entry_d]
  type = "menu"
  order = 12
  [entry_d.entry_d1]
    type = "default"
    order = 1
    menu = "entry d.1"
